### ISSUE TITLE
mix of sycl-blas and sycl kernels

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/portBLAS#193]
To get people started quickly, I think this example is helpful.
There are two SYCL kernels: the first kernel produces results read by the second kernel. The first one is a general kernel while the second one uses sycl-blas. It is not clear if we can pass 'output_d' to the sycl-blas function directly. All the sycl-blas examples assume the inputs are initialized on the host before calling  'make_sycl_iterator_buffer'. 

Can we declare the input buffers to the sycl-blas functions using the general 'buffer<type, 1>' ?  

Thanks for your guide.

sycl:
buffer<float, 1> output_d (n);

sycl-blas
auto a_gpu = blas::make_sycl_iterator_buffer<float>(A, n); // auto a_gpu = output_d ?

**Comment by s-Nick** [comment]
Hi @jinz2014,
I hope you are still interested in portBLAS, we have made a lot of improvements during these years. Back to you question, the best way to achieve what you are trying to do with buffers would require to use a public constructor of `BufferIterators` [here](https://github.com/codeplaysoftware/portBLAS/blob/master/include/container/sycl_iterator.h#L131. It requires only a buffer as argument.
A very simple example would be the following:
```c++
{
    sycl::buffer<float> b_v(v);
    sycl::buffer<float> res_1_b(res_1);
    q.submit([&](sycl::handler& cgh){
        sycl::accessor<float> acc_v{b_v, cgh};
        sycl::accessor<float> acc_res{res_1_b, cgh};
        cgh.parallel_for(sycl::nd_range<1>{1024,256}, [=](sycl::nd_item<1>
  item){ const auto x_id = item.get_global_linear_id(); acc_res[x_id] =
  acc_v[x_id] + 1;
            });
        });
    auto tmp = blas::BufferIterator<float>(res_1_b);
    auto tmp2 = blas::make_sycl_iterator_buffer<float>(res_2, 1);
    auto event = blas::_asum(sb, my_size, tmp, 1, tmp2,{});
  }
```

Where `tmp` var is using `res_1_b` buffer and it is passed to `asum`  operator. You cannot pass directly the buffer to portBLAS operator.
I hope this clarifies your doubt.

**Comment by Rbiessy** [comment]
Closing as this should not be an issue anymore.
