### ISSUE TITLE
 `error: use of undeclared identifier 'sycl'` while building portBLAS with AdaptiveCpp

### ISSUE THREAD

**Issue by krishvishal** [codeplaysoftware/portBLAS#514]
I am trying to build portBLAS with AdaptiveCpp but I keep getting `error: use of undeclared identifier 'sycl'`.

Build command: 
```bash
export ACPP_TARGETS=generic

cmake -GNinja -DTUNING_TARGET=NVIDIA_GPU -DCMAKE_BUILD_TYPE=Release       -DSYCL_COMPILER=adaptivecpp -DACPP_TARGETS=$ACPP_TARGETS       -DBLAS_ENABLE_BENCHMARK=ON ..
```

Environment:
Ubuntu 20.04 (WSL2)
Clang17
AdaptiveCpp built from source

Full stacktrace: https://pastebin.com/k0iW2HqR

**Comment by s-Nick** [comment]
Hi @krishvishal, 
we recently merged PR #513 that fixes the issue you encountered. Could you please update your portBLAS repository and try again?
